### ISSUE TITLE
Crash when unwrapping Error()

### ISSUE THREAD

**Issue by ardhitama** [getsentry/raven-go#232]
go ver: `1.11`

dep:
```
[[projects]]
  digest = "1:bd1b9cbca8127056a93ebacb5ff7c7ceb8f5694b16399daeb242510cce3eae70"
  name = "github.com/getsentry/raven-go"
  packages = ["."]
  pruneopts = "NT"
  revision = "f04e7487e9a6b9d9837d52743fb5f40576c56411"
  version = "v0.2.0"
```

stacktrace:
```
unexpected fault address 0x6e6f697461
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x6e6f697461 pc=0x6e6f697461]
goroutine 73047646 [running]:
runtime.throw(0x10573be, 0x5)
#011/usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc001c070c0 sp=0xc001c07090 pc=0x4376d2
runtime.sigpanic()
#011/usr/local/go/src/runtime/signal_unix.go:397 +0x275 fp=0xc001c07110 sp=0xc001c070c0 pc=0x44cc85
net/url.(*Error).Error(0xc0014e67d0, 0xcbfae2, 0xc0001ee880)
#011/usr/local/go/src/net/url/url.go:28 +0x38 fp=0xc001c07188 sp=0xc001c07110 pc=0x517b28
[project path]/vendor/github.com/getsentry/raven-go.(*Client).CaptureError(0xc0002401e0, 0x12241a0, 0xc0014e67d0, 0xc001c07398, 0x0, 0x0, 0x0, 0xc001ab1740, 0xc0014e67d0)
#011/.go/src/[project path]/vendor/github.com/getsentry/raven-go/client.go:705 +0x63 fp=0xc001c07240 sp=0xc001c07188 pc=0xb5c663
```

**Comment by ardhitama** [comment]
when I really look at it, the bug might be in net/url/url.go

**Comment by mattrobenolt** [comment]
Are you able to share something that can reproduce this? Unfortunately, the data shared isn't enough to investigate more. :(

**Comment by ardhitama** [comment]
this is not sentry problem, please closing this.
context: https://github.com/gojektech/heimdall/issues/63
