### ISSUE TITLE
Nil packet Interface causes panic

### ISSUE THREAD

**Issue by xsleonard** [getsentry/raven-go#64]
When nil is included in the `...raven.Interface` arguments, `panic: runtime error: invalid memory address or nil pointer dereference` occurs in the http transport worker.

Example:

```
package main

import (
    "time"
    "github.com/getsentry/raven-go"
)

func main() {
    dsn := "https://12312312:123123123@app.getsentry.com/231231" // any valid looking dsn, doesn't matter
    c, err := raven.NewClient(dsn, nil)
    if err != nil {
        panic(err)
    }
    defer c.Close()
    msg := "msg"
    tags := map[string]string{"foo": "bar"}
    c.CaptureMessage(msg, tags, nil) // extra nil raven.Interface
    time.Sleep(time.Second * 3)
}
```

```
$ go run main.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x473a7a]

goroutine 21 [running]:
github.com/getsentry/raven-go.(*Packet).JSON(0xc8200c8500, 0x0, 0x0, 0x0)
	/home/steve/.gvm/pkgsets/go1.5/raven-go/src/github.com/getsentry/raven-go/client.go:238 +0x15a
github.com/getsentry/raven-go.serializedPacket(0xc8200c8500, 0x0, 0x0, 0x0, 0x0)
	/home/steve/.gvm/pkgsets/go1.5/raven-go/src/github.com/getsentry/raven-go/client.go:682 +0x58
github.com/getsentry/raven-go.(*HTTPTransport).Send(0xc820085470, 0xc8200854d0, 0x2b, 0xc8200a2780, 0x45, 0xc8200c8500, 0x0, 0x0)
	/home/steve/.gvm/pkgsets/go1.5/raven-go/src/github.com/getsentry/raven-go/client.go:664 +0x6a
github.com/getsentry/raven-go.(*Client).worker(0xc8200de160)
	/home/steve/.gvm/pkgsets/go1.5/raven-go/src/github.com/getsentry/raven-go/client.go:421 +0x166
created by github.com/getsentry/raven-go.newClient
	/home/steve/.gvm/pkgsets/go1.5/raven-go/src/github.com/getsentry/raven-go/client.go:304 +0x192

goroutine 1 [sleep]:
time.Sleep(0xb2d05e00)
	/home/steve/.gvm/gos/go1.5/src/runtime/time.go:59 +0xf9
main.main()
	/tmp/rvn/2/main.go:18 +0x210

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/home/steve/.gvm/gos/go1.5/src/runtime/asm_amd64.s:1696 +0x1

goroutine 20 [chan receive]:
github.com/getsentry/raven-go.(*Client).worker(0xc8200de0b0)
	/home/steve/.gvm/pkgsets/go1.5/raven-go/src/github.com/getsentry/raven-go/client.go:415 +0x60
created by github.com/getsentry/raven-go.newClient
	/home/steve/.gvm/pkgsets/go1.5/raven-go/src/github.com/getsentry/raven-go/client.go:304 +0x192
exit status 2
```

**Comment by mattrobenolt** [comment]
Thanks for the report. :) I'll get this patched soon.
